#
# Makefile for ALSA
#

snd-au1x00-objs := au1x00.o
snd-nxc2600-objs := nxc2600.o

# Toplevel Module Dependency
obj-$(CONFIG_SND_AU1X00) += snd-au1x00.o
obj-$(CONFIG_SND_NXC2600_AC97) += snd-nxc2600.o
